from pathlib import Path
from xml.sax.saxutils import escape as E
import zipfile, json
W=Path('/Users/konnco5204/Desktop/Workshop MAAS')
slides=[
('Workshop Konnco Studio\nfea Heawei Cloud','Cloud Log Analyzer dengan Huawei MaaS API\n\nby DevOps/SRE Konnco','30 menit. Audiens: SRE / DevOps dengan dasar HTML dan JavaScript. Judul mengikuti permintaan pengguna.'),
('Hasil workshop','Web app untuk membaca log error dan stack trace\nAnalisis penyebab, severity, dampak, pemulihan, dan pencegahan\nFollow-up chat dengan konteks percakapan\nLatihan dimulai dari satu file index.html','Demo final sebelum coding. Peserta membangun versi minimal sesuai guide. Aplikasi demo dalam proyek menggunakan berkas CSS dan JS terpisah.'),
('Agenda 30 menit','00–05   Pengenalan dan demo aplikasi\n05–10   Setup akun, model, dan API key\n10–25   Live coding bersama peserta\n25–30   Eksperimen, demo, dan tanya jawab','Alokasi waktu mengikuti WORKSHOP_GUIDE.md.'),
('AI sebagai asisten analisis log','Input: log error atau stack trace\nOutput: dugaan penyebab dan langkah pemeriksaan\nSRE memeriksa bukti sebelum menjalankan perbaikan\nDemo awal: Kubernetes CrashLoopBackOff','Guide memuat klaim percepatan diagnosis tanpa sumber pengukuran. Deck tidak menyajikan angka tersebut sebagai hasil yang terbukti.'),
('Setup Huawei MaaS','1. Login ke console.huaweicloud.com\n2. Buka ModelArts / MaaS / Model Square\n3. Aktifkan akses model yang tersedia di akun\n4. Buat API key, lalu simpan secara privat','Guide menggunakan model GLM-5.2. Nama menu, model, akses trial, dan endpoint perlu dicocokkan dengan console akun saat workshop. Fasilitator menyiapkan akses cadangan terbatas.'),
('Konfigurasi latihan','MODEL = "GLM-5.2"\n\nPOST /v1/chat/completions\nAuthorization: Bearer YOUR_API_KEY\nContent-Type: application/json','Endpoint contoh dalam guide: https://api-ap-southeast-1.modelarts-maas.com/v1/chat/completions. Cocokkan endpoint dan model dengan akun. Jangan tampilkan key asli pada proyektor atau commit ke repository.'),
('Alur aplikasi','01   Peserta memasukkan log di browser\n02   JavaScript mengirim messages ke MaaS\n03   API mengembalikan teks analisis\n04   UI menampilkan hasil dan menyimpan history','Request memakai fetch dan JSON. Untuk demo lokal, panggilan langsung bergantung pada dukungan CORS. Untuk penggunaan bersama, gunakan backend proxy agar API key berada di server.'),
('Step 1  ·  Skeleton HTML','<h1>Cloud Log Analyzer</h1>\n<textarea id="log-input"></textarea>\n<button onclick="analyzeLog()">\n  Analisis dengan AI\n</button>\n<pre id="output"></pre>','2 menit. Buat index.html lengkap dengan doctype, html lang=id, head, meta charset UTF-8, title, dan body. Potongan slide menunjukkan elemen inti. pre menjaga baris hasil tetap terbaca.'),
('Step 2  ·  Request API','const response = await fetch(ENDPOINT, {\n  method: "POST",\n  headers: { "Content-Type": "application/json",\n    Authorization: `Bearer ${API_KEY}` },\n  body: JSON.stringify({ model: MODEL, messages,\n    max_tokens: 1000, temperature: 0.3 })\n});','3 menit bersama slide berikut. Letakkan dalam fungsi async. messages berisi system prompt dan log pengguna. ENDPOINT, API_KEY, MODEL mengikuti konfigurasi. Parameter 0.3 mengikuti guide dan tidak menjamin jawaban benar.'),
('System prompt dan hasil respons','SYSTEM\nKamu adalah asisten SRE. Jelaskan root cause,\nseverity, dampak, langkah fix, dan pencegahan.\n\nHASIL\nconst data = await response.json();\nreturn data.choices[0].message.content;','Susun messages sebagai [{role:"system",content:SYSTEM_PROMPT},{role:"user",content:userMessage}]. Tambahkan pemeriksaan response.ok dan keberadaan choices sebelum membaca hasil. Minta model membedakan bukti log dari dugaan.'),
('Step 3  ·  UI dan loading state','Input kosong        Tampilkan petunjuk untuk mengisi log\nRequest berjalan    Tampilkan “Menganalisis...”\nRequest berhasil    Isi output dengan textContent\nRequest gagal       Tampilkan pesan error yang jelas','3 menit. Ambil log-input.value.trim(). Gunakan try/catch dan await callMaasAPI(). Gunakan textContent saat menampilkan hasil minimal. Demo dengan sample OutOfMemoryError.'),
('Step 4  ·  Conversation history','Log baru memulai history baru\nSystem prompt dan log menjadi pesan awal\nSetiap jawaban masuk sebagai role: "assistant"\nFollow-up masuk sebagai role: "user"\nRequest berikutnya mengirim seluruh history','4 menit. let conversationHistory = []; setelah respons: conversationHistory.push({role:"assistant",content:aiReply}); sebelum follow-up: push({role:"user",content:question}). API tidak menyimpan konteks aplikasi ini secara otomatis. Tambahkan input id=followup dan tombol sendFollowup().'),
('Step 5  ·  Demo versi final','Pilihan sample log untuk beberapa jenis insiden\nLoading state selama analisis berjalan\nFollow-up chat setelah jawaban pertama\nPengaturan API key di aplikasi demo','3 menit. Buka index.html proyek. Guide menyebut penyimpanan API key di localStorage. Jelaskan sebagai kemudahan demo lokal, dengan backend proxy untuk aplikasi bersama. Tunjukkan dark mode dan sample log.'),
('Latihan  ·  OutOfMemoryError','LOG\njava.lang.OutOfMemoryError: Java heap space\nGC overhead limit exceeded\nHealth check FAILED - service unresponsive\n\nFOLLOW-UP\n“Bagaimana cara monitor ini pakai Prometheus?”','Sample diringkas dari js/config.js. Peserta memeriksa apakah model menghubungkan heap, GC, dan health check. Log ini belum cukup untuk memastikan memory leak. Gunakan log contoh atau log yang sudah disamarkan.'),
('Troubleshooting','401       Periksa API key dan format Bearer\n404       Periksa endpoint, model, dan akses akun\nCORS      Periksa akses browser, gunakan proxy bila perlu\nKosong    Periksa status HTTP dan struktur response','Ikuti troubleshooting guide. Status 404 tidak sendirinya memastikan subscription bermasalah. Saat debug, hindari membagikan header Authorization atau log sensitif. Lihat data.choices[0].message.content setelah validasi.'),
('Diskusi dan eksperimen','Apa bukti log yang mendukung dugaan root cause?\nApa yang berubah jika system prompt lebih spesifik?\nBagaimana menyamarkan data sensitif sebelum request?\nApa pemeriksaan sebelum menjalankan saran perbaikan?','5 menit terakhir bersama demo. Jawab biaya dan akses model dengan merujuk console akun, tanpa menjanjikan free tier. Untuk integrasi Slack atau PagerDuty, bahas sebagai pengembangan lanjutan.'),
('Pengembangan berikutnya','Perbandingan beberapa log\nGenerator runbook Markdown\nIntegrasi API dalam script monitoring\nSaran routing alert untuk review tim','Bonus dari guide. Peserta dapat mengembangkan salah satu setelah sesi 30 menit. Integrasi alert perlu mekanisme review sebelum mengirim atau menjalankan tindakan.'),
('Checklist fasilitator','Akun, API key, endpoint, dan model sudah diuji\nDemo index.html berhasil dari browser yang dipakai\nSample log dan akses cadangan siap\nEditor terbuka untuk live coding\n\nTerima kasih\nby DevOps/SRE Konnco','Sumber utama seluruh deck: WORKSHOP_GUIDE.md. Contoh OOM: js/config.js. Persiapan sebelum sesi: uji kemungkinan CORS dan siapkan proxy jika dibutuhkan. Jangan bagikan key cadangan secara terbuka.')]
A='http://schemas.openxmlformats.org/drawingml/2006/main';P='http://schemas.openxmlformats.org/presentationml/2006/main';R='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
def rel(items): return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+''.join(f'<Relationship Id="rId{i}" Type="{R}/{t}" Target="{p}"/>' for i,t,p in items)+'</Relationships>'
def box(i,x,y,w,h,text,size,color='F2F4F8',bold=False,font='Aptos'):
 pars=''.join(f'<a:p><a:pPr><a:lnSpc><a:spcPct val="115000"/></a:lnSpc></a:pPr><a:r><a:rPr lang="id-ID" sz="{size*100}" b="{int(bold)}"><a:solidFill><a:srgbClr val="{color}"/></a:solidFill><a:latin typeface="{font}"/></a:rPr><a:t xml:space="preserve">{E(line)}</a:t></a:r><a:endParaRPr lang="id-ID" sz="{size*100}"/></a:p>' for line in text.split('\n'))
 return f'<p:sp><p:nvSpPr><p:cNvPr id="{i}" name="Text {i}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="{int(x*12700)}" y="{int(y*12700)}"/><a:ext cx="{int(w*12700)}" cy="{int(h*12700)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr wrap="square" lIns="0" rIns="0" tIns="0" bIns="0"/><a:lstStyle/>{pars}</p:txBody></p:sp>'
grp='<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>'
files={}
files['_rels/.rels']=rel([(1,'officeDocument','ppt/presentation.xml')])
files['ppt/presentation.xml']=f'<p:presentation xmlns:p="{P}" xmlns:a="{A}" xmlns:r="{R}"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>'+''.join(f'<p:sldId id="{256+i}" r:id="rId{i+2}"/>' for i in range(len(slides)))+'</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>'
files['ppt/_rels/presentation.xml.rels']=rel([(1,'slideMaster','slideMasters/slideMaster1.xml')]+[(i+2,'slide',f'slides/slide{i+1}.xml') for i in range(len(slides))])
files['ppt/slideMasters/slideMaster1.xml']=f'<p:sldMaster xmlns:p="{P}" xmlns:a="{A}" xmlns:r="{R}"><p:cSld><p:spTree>{grp}</p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>'
files['ppt/slideMasters/_rels/slideMaster1.xml.rels']=rel([(1,'slideLayout','../slideLayouts/slideLayout1.xml'),(2,'theme','../theme/theme1.xml')])
files['ppt/slideLayouts/slideLayout1.xml']=f'<p:sldLayout xmlns:p="{P}" xmlns:a="{A}" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree>{grp}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>'
files['ppt/slideLayouts/_rels/slideLayout1.xml.rels']=rel([(1,'slideMaster','../slideMasters/slideMaster1.xml')])
colors=['111827','FFFFFF','182338','E9EEF5','55D6BE','EF5670','6BA3FF','E9C46A','9C89B8','E07A5F','6BA3FF','9C89B8']
names=['dk1','lt1','dk2','lt2','accent1','accent2','accent3','accent4','accent5','accent6','hlink','folHlink']
files['ppt/theme/theme1.xml']=f'<a:theme xmlns:a="{A}" name="Konnco"><a:themeElements><a:clrScheme name="Konnco">'+''.join(f'<a:{n}><a:srgbClr val="{c}"/></a:{n}>' for n,c in zip(names,colors))+'</a:clrScheme><a:fontScheme name="Aptos"><a:majorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="Simple"><a:fillStyleLst/><a:lnStyleLst/><a:effectStyleLst/><a:bgFillStyleLst/></a:fmtScheme></a:themeElements></a:theme>'
for i,(title,body,notes) in enumerate(slides,1):
 cover=i==1; code=i in [6,8,9,10,14]; size=20 if code else 24
 shapes=box(2,54,90 if cover else 45,850,140 if cover else 85,title,42 if cover else 32,'55D6BE',True)
 shapes+=box(3,54,275 if cover else 165,850,240 if cover else 310,body,size if not cover else 24,font='Consolas' if code else 'Aptos')
 shapes+=box(4,54,510,850,18,f'KONNCO STUDIO    /    Cloud LOG ANALYZER                                      {i:02d}',10,'9BA8BA')
 files[f'ppt/slides/slide{i}.xml']=f'<p:sld xmlns:p="{P}" xmlns:a="{A}" xmlns:r="{R}"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="111827"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree>{grp}{shapes}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>'
 files[f'ppt/slides/_rels/slide{i}.xml.rels']=rel([(1,'slideLayout','../slideLayouts/slideLayout1.xml'),(2,'notesSlide',f'../notesSlides/notesSlide{i}.xml')])
 nb=box(2,40,40,600,800,notes+'\n\nSumber: WORKSHOP_GUIDE.md',14).replace('<p:nvPr/>','<p:nvPr><p:ph type="body" idx="1"/></p:nvPr>')
 files[f'ppt/notesSlides/notesSlide{i}.xml']=f'<p:notes xmlns:p="{P}" xmlns:a="{A}" xmlns:r="{R}"><p:cSld><p:spTree>{grp}{nb}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:notes>'
 files[f'ppt/notesSlides/_rels/notesSlide{i}.xml.rels']=rel([(1,'slide',f'../slides/slide{i}.xml')])
ct={'presentation':'presentation.main','slideMasters':'slideMaster','slideLayouts':'slideLayout','slides':'slide','notesSlides':'notesSlide'}
ov=[]
for k in files:
 if not k.endswith('.xml'): continue
 typ='application/vnd.openxmlformats-officedocument.theme+xml' if '/theme/' in k else 'application/vnd.openxmlformats-officedocument.presentationml.'+(ct['presentation'] if k=='ppt/presentation.xml' else ct[k.split('/')[1]])+'+xml'
 ov.append(f'<Override PartName="/{k}" ContentType="{typ}"/>')
files['[Content_Types].xml']='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>'+''.join(ov)+'</Types>'
out=W/'output/Workshop_Konnco_Studio.pptx'
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
 for k,v in files.items(): z.writestr(k,v)
(W/'.pptx-build/slides.json').write_text(json.dumps(slides,ensure_ascii=False))
print(out)
